[package]
name = "rs-bookmark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.28.0"
clap = { version="3.2.22", features=["cargo", "derive"] }
semver = "1.0.14"
regex = "1.6.0"