[package]
name = "rs-wc"
version = "0.1.0"
edition = "2021"

description = "Print newline, bytes counts for each FILE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version="3.2.22", features=['cargo']}
